INSERT INTO nome_tabela (coluna1, coluna2, coluna3...)
VALUES (valor_coluna1, valor_coluna2, valor_coluna3...)
(valor_coluna1, valor_coluna2, valor_coluna3...)
(valor_coluna1, valor_coluna2, valor_coluna3...)
(valor_coluna1, valor_coluna2, valor_coluna3...)